removed tiny_thread from project: was causing compilation errors.
git-svn-id: https://apollo.arh.pub.ro:8443/svn/ConnexSIFT/trunk/software/connex@168 0e9f8c0c-05a5-1044-940b-b810a0af9d24